/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface BenDatePicker {}
  interface BenDatePickerAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'BenDatePicker': Components.BenDatePicker;
  }

  interface StencilIntrinsicElements {
    'ben-date-picker': Components.BenDatePickerAttributes;
  }


  interface HTMLBenDatePickerElement extends Components.BenDatePicker, HTMLStencilElement {}
  var HTMLBenDatePickerElement: {
    prototype: HTMLBenDatePickerElement;
    new (): HTMLBenDatePickerElement;
  };

  interface HTMLElementTagNameMap {
    'ben-date-picker': HTMLBenDatePickerElement
  }

  interface ElementTagNameMap {
    'ben-date-picker': HTMLBenDatePickerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
